server:
  port: 8088
spring:
  application:
    name: event-stream
  datasource:
    url: jdbc:h2:file:./data/eventdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 0

events:
  task-processor-interval-ms: 1000
  task-processor-batch-size: 100
  task-in-progress-timeout-seconds: 30
  kafka:
    topic: live-events-scores
    max-retries: 3

external:
  api:
    base-url: http://localhost:8088/mock-api
    connect-timeout-ms: 1000
    read-timeout-ms: 2000
